spring.application.name=to-do-list

spring.datasource.url=jdbc:postgresql:5432/to-do-list
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true